GET http://localhost:8080/user

###
GET http://localhost:8080/user/list?page=1&size=500

###
PUT http://localhost:8080/user/1/password
Content-type:application/json

{
  "password": "TEST1234"
}

###
POST http://localhost:8080/login
Content-type:application/json

{
  "loginName": "user",
  "password": "user"
}
###
PUT http://localhost:8080/user/role
Content-type:application/json

{
  "id": 1,
  "role": "ROLE_USER"
}